server:
  port: 7001
spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.203.107:3306/gulimall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: lishicheng11400
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: admin
  config:
    import:
      - optional:nacos:admin-myconfig.yaml?refreshEnabled=true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto